In [1]:
# 1
import pandas as pd
df = pd.read_csv("./student_sample_data.csv")
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.83,7,1,4,0,0,1,0,3.60,0.0
1,1002,18,0,0,1,15.41,0,0,1,0,0,0,0,3.40,0.0
2,1003,15,0,2,3,4.21,26,0,2,0,0,0,0,1.48,4.0
3,1004,17,1,0,3,10.03,14,0,3,1,0,0,0,2.20,3.0
4,1005,16,1,0,2,4.67,17,1,3,0,0,0,0,1.38,4.0

In [2]:
# 2
print(df.isnull().sum())
print(df.describe())
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64
         StudentID        Age    Gender  Ethnicity  ParentalEducation  \
count     5.000000   5.000000  5.000000   5.000000            5.00000
mean   1003.000000  16.600000  0.600000   0.400000            2.20000
std       1.581139   1.140175  0.547723   0.894427            0.83666
min    1001.000000  15.000000  0.000000   0.000000            1.00000
25%    1002.000000  16.000000  0.000000   0.000000            2.00000
50%    1003.000000  17.000000  1.000000   0.000000            2.00000
75%    1004.000000  17.000000  1.000000   0.000000            3.00000
max    1005.000000  18.000000  1.000000   2.000000            3.00000

       StudyTimeWeekly   Absences  Tutoring  ParentalSupport  Extracurricular  \
count         5.000000   5.000000  5.000000         5.000000         5.000000
mean         10.830000  12.800000  0.400000         2.600000         0.200000
std           6.789448   9.884331  0.547723         1.140175         0.447214
min           4.210000   0.000000  0.000000         1.000000         0.000000
25%           4.670000   7.000000  0.000000         2.000000         0.000000
50%          10.030000  14.000000  0.000000         3.000000         0.000000
75%          15.410000  17.000000  1.000000         3.000000         0.000000
max          19.830000  26.000000  1.000000         4.000000         1.000000

       Sports     Music  Volunteering       GPA  GradeClass
count     5.0  5.000000           5.0  5.000000     5.00000
mean      0.0  0.200000           0.0  2.412000     2.20000
std       0.0  0.447214           0.0  1.044758     2.04939
min       0.0  0.000000           0.0  1.380000     0.00000
25%       0.0  0.000000           0.0  1.480000     0.00000
50%       0.0  0.000000           0.0  2.200000     3.00000
75%       0.0  0.000000           0.0  3.400000     4.00000
max       0.0  1.000000           0.0  3.600000     4.00000
Rows: 5
Columns: 15

In [3]:
# 3
print(df.dtypes)
df['Age']=df['Age'].astype('category')
df['Ethnicity']=df['Ethnicity'].astype('category')
df['GPA']=df['GPA'].astype('category')
df['Gender']=df['Gender'].astype('category')
print(df.dtypes)

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object
StudentID               int64
Age                  category
Gender               category
Ethnicity            category
ParentalEducation       int64
StudyTimeWeekly       float64
Absences                int64
Tutoring                int64
ParentalSupport         int64
Extracurricular         int64
Sports                  int64
Music                   int64
Volunteering            int64
GPA                  category
GradeClass            float64
dtype: object

In [4]:
# 4
df_encoded=pd.get_dummies(df,columns=['Age','GPA','Gender'])
df_encoded.head()

,StudentID,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,...,Age_16,Age_17,Age_18,GPA_1.38,GPA_1.48,GPA_2.2,GPA_3.4,GPA_3.6,Gender_0,Gender_1
0,1001,0,2,19.83,7,1,4,0,0,1,...,False,True,False,False,False,False,False,True,False,True
1,1002,0,1,15.41,0,0,1,0,0,0,...,False,False,True,False,False,False,True,False,True,False
2,1003,2,3,4.21,26,0,2,0,0,0,...,False,False,False,False,True,False,False,False,True,False
3,1004,0,3,10.03,14,0,3,1,0,0,...,False,True,False,False,False,True,False,False,False,True
4,1005,0,2,4.67,17,1,3,0,0,0,...,True,False,False,True,False,False,False,False,False,True